# SEALED SECRET — Staging Environment
#
# Para regenerar:
#   kubectl create secret generic circleguard-secret \
#     --namespace=circleguard-stage \
#     --from-literal=POSTGRES_PASSWORD=<real_pass> \
#     --from-literal=NEO4J_PASSWORD=<real_pass> \
#     --from-literal=JWT_SECRET=<real_secret_min_32_chars> \
#     --from-literal=QR_SECRET=<real_qr_secret> \
#     --from-literal=VAULT_SECRET=<real_vault_secret> \
#     --from-literal=VAULT_SALT=<real_salt> \
#     --from-literal=VAULT_HASH_SALT=<real_hash_salt> \
#     --from-literal=LDAP_MANAGER_PASSWORD=<real_ldap_pass> \
#     --dry-run=client -o yaml | \
#   kubeseal --controller-name=sealed-secrets \
#            --controller-namespace=kube-system \
#            --format yaml > k8s/secrets/sealed-secret-stage.yml

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: circleguard-secret
  namespace: circleguard-stage
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    POSTGRES_PASSWORD: REPLACE_WITH_KUBESEAL_OUTPUT
    NEO4J_PASSWORD: REPLACE_WITH_KUBESEAL_OUTPUT
    JWT_SECRET: REPLACE_WITH_KUBESEAL_OUTPUT
    QR_SECRET: REPLACE_WITH_KUBESEAL_OUTPUT
    VAULT_SECRET: REPLACE_WITH_KUBESEAL_OUTPUT
    VAULT_SALT: REPLACE_WITH_KUBESEAL_OUTPUT
    VAULT_HASH_SALT: REPLACE_WITH_KUBESEAL_OUTPUT
    LDAP_MANAGER_PASSWORD: REPLACE_WITH_KUBESEAL_OUTPUT
  template:
    metadata:
      name: circleguard-secret
      namespace: circleguard-stage
    type: Opaque
